name: Dependabot AI Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get PR diff
        run: gh pr diff ${{ github.event.pull_request.number }} > changes.diff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run AI analysis
        id: ai
        run: |
          SUMMARY=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are a code reviewer analyzing dependency updates.\"},
                {\"role\": \"user\", \"content\": \"Analyze these dependency update changes and highlight risks, breaking changes, or security concerns:\n$(cat changes.diff)\"}
              ]
            }" | jq -r '.choices[0].message.content')

          echo "summary=$SUMMARY" >> $GITHUB_OUTPUT

      - name: Comment on PR
        run: gh pr comment ${{ github.event.pull_request.number }} --body "${{ steps.ai.outputs.summary }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
